CREATE TABLE sensorData(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	temperatureVal DOUBLE NOT NULL,
	currentVal DOUBLE NOT NULL,
	vibrationVal DOUBLE NOT NULL,
	rpmVal BIGINT NOT NULL,
	receivedTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);